In [2]:
from open3d import *
import scipy.io
import pandas as pd
import numpy as np
import glob
import os

In [69]:
def load_file(filedir):
    mat = scipy.io.loadmat(filedir)
    try:
        points = mat["points"]
    except KeyError as e:
        print(f'Could not load {file} file -> KeyError: {e}')
        return []
    return points

def read_pcd(file):
    return read_point_cloud(file)

def write_pcd(filedir, points):
    pcd = PointCloud()
    pcd.points = Vector3dVector(points)
    write_point_cloud(filedir, pcd)

def mat_to_pcd(filedir, extension, newdir):
    files = glob.glob(filedir+"/*"+extension)
    if not os.path.exists(newdir):
        os.mkdir(newdir)
        print(newdir+" directory created")
    for file in files:
        points = load_file(file)
        if len(points) != 0:
            filename = file.split(".")[0]+".ply"
            filename = filename.split("/")[-1]
            filename = newdir+filename
            if not os.path.exists(filename):
                write_pcd(filename, points)


def create_model(filedir):
    data = []
    with open(filedir) as f:
        file = f.read().splitlines()
        for item in file:
            item = item.split(' ')
            new_item = []
            for e in item:
                if e != '':
                    new_item.append(e)
            data.append(new_item)
    vertices = []
    triangles = []
    for i in range(int(data[0][0])):
        vertices.append(list(map(float, data[i+1][:3])))

    for i in range(int(data[0][1])):
        triangles.append(list(map(int, data[i+int(data[0][0])+1])))
        
    mesh = open3d.geometry.TriangleMesh()
    mesh.vertices = Vector3dVector(np.array(vertices))
    mesh.triangles = Vector3iVector(np.array(triangles))
    mesh.compute_triangle_normals()
    mesh.compute_vertex_normals()
    return mesh

In [16]:
filedir = '/Users/nickf/Desktop/Custom-Fit/Data/Body-Datasets/Caesar-Data/caesar/meanshape.mat'
mat = scipy.io.loadmat(filedir)

In [17]:
for key in mat.keys():
    print(f'{key}:{mat[key]}')

__header__:b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Tue Aug 12 11:40:25 2014'
__version__:1.0
__globals__:[]
points:[[-1.33926000e-03  9.05487000e+01  7.99718000e+02]
 [-2.13881107e-01  7.99444097e+01  8.08583799e+02]
 [ 4.47694323e-01  9.94668743e+01  7.94246374e+02]
 ...
 [ 1.63805135e+02  2.37000950e+01  4.74036037e+01]
 [ 1.59371085e+02  4.62206403e+01  4.26767205e+01]
 [ 1.72352888e+02  7.94995389e+01  4.25441082e+01]]


In [67]:
filename = "/Users/nickf/Desktop/Body-Datasets/Caesar-Data/caesar-norm-wsx/model.dat"
mesh = create_model(filename)
draw_geometries([mesh])

In [65]:
filedir = "/Users/nickf/Desktop/Body-Datasets/Caesar-Data/caesar-norm-wsx-fitted-meshes/"
extension = ".mat"
newdir = "/Users/nickf/Desktop/Body-Datasets/Caesar-Data/CSRNWSXFM_PCD/"
mat_to_pcd(filedir, extension, newdir)

6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449


6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449


6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449
6449


In [76]:
filename = "/Users/nickf/Desktop/Body-Datasets/Caesar-Data/CSRFM_PCD/CSR1729A.ply"
pcd_load = read_pcd(filename)

In [77]:
draw_geometries([pcd_load])